# Generated by Django 4.2.7 on 2023-12-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.sgv', null=True, upload_to=''),
        ),
    ]
