# Generated by Django 4.2.7 on 2024-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
    ]
