# Generated by Django 4.2.7 on 2023-12-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
