# Generated by Django 4.2.7 on 2023-12-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='proImg',
            field=models.ImageField(default='defaut1.png', upload_to='profile_images/'),
        ),
    ]
