# Generated by Django 4.2.7 on 2023-12-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_room_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
