# Generated by Django 4.2.7 on 2023-12-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_proimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
