# Generated by Django 4.2.7 on 2023-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_profile_bio_remove_profile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='proImg',
            field=models.ImageField(default='defaut1.png', null=True, upload_to='profile_images/'),
        ),
    ]
