# Generated by Django 4.2.7 on 2023-12-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
    ]
