# Generated by Django 4.2.7 on 2023-12-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_proimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
    ]
