# Generated by Django 4.2.7 on 2023-12-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_userprofile_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to='base.userprofile'),
        ),
    ]
