# Generated by Django 4.2.7 on 2023-12-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
